name: PlayerPing
main: org.imaginecraft.playerping.PlayerPing
version: 2.0.0
authors:
    - CyberDrain
description: A very simple plugin to check pings
commands:
    ping:
        description: check ping
        usage: /ping [player]
        